version: 2

models:
    - name: customer_data
      description: "A model of full customer data"
      columns:
          - name: customer_id
            description: "The customer id"
            tests:
                - unique
                - not_null
